-- ─────────────────────────────────────────────────────────────────────────────
-- AutoParts Manager — Supabase (Postgres) schema
--
-- Run this entire file in the Supabase SQL Editor once:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- Design notes:
--   • UUIDs for all primary keys — matches the IDs generated by Dexie on the
--     client (use crypto.randomUUID() when inserting locally).
--   • updated_at is set automatically by a trigger on every UPDATE so you
--     don't have to remember to set it in application code.
--   • Row-Level Security (RLS) is enabled on every table. The policy grants
--     full access only to the authenticated user — no anonymous reads.
--   • Foreign keys are declared but NOT set to CASCADE DELETE by default,
--     so you won't accidentally wipe child rows during a sync upsert.
-- ─────────────────────────────────────────────────────────────────────────────

-- Helper: auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ─── SUPPLIERS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suppliers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  phone         TEXT,
  balance_owed  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER suppliers_updated_at
  BEFORE UPDATE ON suppliers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON suppliers
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── CUSTOMERS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  phone         TEXT,
  credit_limit  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  balance_owed  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON customers
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PRODUCTS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL,
  sku              TEXT,
  category         TEXT,
  cost_price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
  selling_price    NUMERIC(12, 2) NOT NULL DEFAULT 0,
  qty_warehouse    INTEGER NOT NULL DEFAULT 0,
  qty_store        INTEGER NOT NULL DEFAULT 0,
  reorder_level    INTEGER NOT NULL DEFAULT 0,
  supplier_id      UUID REFERENCES suppliers(id) ON DELETE SET NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON products
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── SALES ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date           DATE NOT NULL DEFAULT CURRENT_DATE,
  customer_id    UUID REFERENCES customers(id) ON DELETE SET NULL,
  payment_method TEXT,          -- 'cash' | 'credit' | 'mobile_money' | etc.
  status         TEXT NOT NULL DEFAULT 'completed',  -- 'completed' | 'pending' | 'cancelled'
  total          NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER sales_updated_at
  BEFORE UPDATE ON sales
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON sales
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── SALE ITEMS ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sale_items (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id     UUID NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id  UUID REFERENCES products(id) ON DELETE SET NULL,
  quantity    INTEGER NOT NULL DEFAULT 1,
  unit_price  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  subtotal    NUMERIC(12, 2) NOT NULL DEFAULT 0
);

ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON sale_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PURCHASES ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchases (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date           DATE NOT NULL DEFAULT CURRENT_DATE,
  supplier_id    UUID REFERENCES suppliers(id) ON DELETE SET NULL,
  payment_status TEXT NOT NULL DEFAULT 'unpaid',  -- 'paid' | 'unpaid' | 'partial'
  total          NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER purchases_updated_at
  BEFORE UPDATE ON purchases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON purchases
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PURCHASE ITEMS ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_items (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_id  UUID NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id) ON DELETE SET NULL,
  quantity     INTEGER NOT NULL DEFAULT 1,
  unit_cost    NUMERIC(12, 2) NOT NULL DEFAULT 0
);

ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON purchase_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── EXPENSES ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expenses (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL DEFAULT CURRENT_DATE,
  category    TEXT,
  amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
  description TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER expenses_updated_at
  BEFORE UPDATE ON expenses
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON expenses
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PAYMENTS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payments (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  related_sale_id     UUID REFERENCES sales(id) ON DELETE SET NULL,
  related_purchase_id UUID REFERENCES purchases(id) ON DELETE SET NULL,
  date                DATE NOT NULL DEFAULT CURRENT_DATE,
  amount              NUMERIC(12, 2) NOT NULL DEFAULT 0,
  method              TEXT,           -- 'cash' | 'mobile_money' | 'bank' | etc.
  direction           TEXT NOT NULL,  -- 'in' (received from customer) | 'out' (paid to supplier)
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced              BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON payments
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── USEFUL INDEXES ──────────────────────────────────────────────────────────
-- Speed up "give me everything updated since timestamp X" (the pull query)
CREATE INDEX ON products    (updated_at);
CREATE INDEX ON customers   (updated_at);
CREATE INDEX ON suppliers   (updated_at);
CREATE INDEX ON sales       (updated_at);
CREATE INDEX ON purchases   (updated_at);
CREATE INDEX ON expenses    (updated_at);
CREATE INDEX ON payments    (updated_at);

-- Speed up joins on foreign keys (Postgres doesn't auto-index FK columns)
CREATE INDEX ON products    (supplier_id);
CREATE INDEX ON sales       (customer_id);
CREATE INDEX ON sale_items  (sale_id);
CREATE INDEX ON sale_items  (product_id);
CREATE INDEX ON purchases   (supplier_id);
CREATE INDEX ON purchase_items (purchase_id);
CREATE INDEX ON purchase_items (product_id);
CREATE INDEX ON payments    (related_sale_id);
CREATE INDEX ON payments    (related_purchase_id);
