-- ─────────────────────────────────────────────────────────────────────────────
-- AutoParts Manager — Supabase (Postgres) schema
--
-- Run this entire file in the Supabase SQL Editor once:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- Design notes:
--   • UUIDs for all primary keys — matches the IDs generated by Dexie on the
--     client (use crypto.randomUUID() when inserting locally).
--   • updated_at is set automatically by a trigger on every UPDATE so you
--     don't have to remember to set it in application code.
--   • Row-Level Security (RLS) is enabled on every table. The policy grants
--     full access only to the authenticated user — no anonymous reads.
--   • Foreign keys are declared but NOT set to CASCADE DELETE by default,
--     so you won't accidentally wipe child rows during a sync upsert.
-- ─────────────────────────────────────────────────────────────────────────────

-- Helper: auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ─── SUPPLIERS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suppliers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  phone         TEXT,
  balance_owed  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER suppliers_updated_at
  BEFORE UPDATE ON suppliers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON suppliers
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── CUSTOMERS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  phone         TEXT,
  credit_limit  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  balance_owed  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON customers
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PRODUCTS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL,
  sku              TEXT,
  category         TEXT,
  cost_price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
  selling_price    NUMERIC(12, 2) NOT NULL DEFAULT 0,
  qty_warehouse    INTEGER NOT NULL DEFAULT 0,
  qty_store        INTEGER NOT NULL DEFAULT 0,
  reorder_level    INTEGER NOT NULL DEFAULT 0,
  supplier_id      UUID REFERENCES suppliers(id) ON DELETE SET NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON products
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── SALES ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date           DATE NOT NULL DEFAULT CURRENT_DATE,
  customer_id    UUID REFERENCES customers(id) ON DELETE SET NULL,
  payment_method TEXT,          -- 'cash' | 'credit' | 'mobile_money' | etc.
  status         TEXT NOT NULL DEFAULT 'completed',  -- 'completed' | 'pending' | 'cancelled'
  total          NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER sales_updated_at
  BEFORE UPDATE ON sales
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON sales
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── SALE ITEMS ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sale_items (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id     UUID NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id  UUID REFERENCES products(id) ON DELETE SET NULL,
  quantity    INTEGER NOT NULL DEFAULT 1,
  unit_price  NUMERIC(12, 2) NOT NULL DEFAULT 0,
  subtotal    NUMERIC(12, 2) NOT NULL DEFAULT 0
);

ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON sale_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PURCHASES ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchases (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date           DATE NOT NULL DEFAULT CURRENT_DATE,
  supplier_id    UUID REFERENCES suppliers(id) ON DELETE SET NULL,
  payment_status TEXT NOT NULL DEFAULT 'unpaid',  -- 'paid' | 'unpaid' | 'partial'
  total          NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER purchases_updated_at
  BEFORE UPDATE ON purchases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON purchases
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PURCHASE ITEMS ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_items (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_id  UUID NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id) ON DELETE SET NULL,
  quantity     INTEGER NOT NULL DEFAULT 1,
  unit_cost    NUMERIC(12, 2) NOT NULL DEFAULT 0
);

ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON purchase_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── EXPENSES ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expenses (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL DEFAULT CURRENT_DATE,
  category    TEXT,
  amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
  description TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER expenses_updated_at
  BEFORE UPDATE ON expenses
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON expenses
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── PAYMENTS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payments (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  related_sale_id     UUID REFERENCES sales(id) ON DELETE SET NULL,
  related_purchase_id UUID REFERENCES purchases(id) ON DELETE SET NULL,
  date                DATE NOT NULL DEFAULT CURRENT_DATE,
  amount              NUMERIC(12, 2) NOT NULL DEFAULT 0,
  method              TEXT,           -- 'cash' | 'mobile_money' | 'bank' | etc.
  direction           TEXT NOT NULL,  -- 'in' (received from customer) | 'out' (paid to supplier)
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced              BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TRIGGER payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON payments
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── USEFUL INDEXES ──────────────────────────────────────────────────────────
-- Speed up "give me everything updated since timestamp X" (the pull query)
CREATE INDEX ON products    (updated_at);
CREATE INDEX ON customers   (updated_at);
CREATE INDEX ON suppliers   (updated_at);
CREATE INDEX ON sales       (updated_at);
CREATE INDEX ON purchases   (updated_at);
CREATE INDEX ON expenses    (updated_at);
CREATE INDEX ON payments    (updated_at);

-- Speed up joins on foreign keys (Postgres doesn't auto-index FK columns)
CREATE INDEX ON products    (supplier_id);
CREATE INDEX ON sales       (customer_id);
CREATE INDEX ON sale_items  (sale_id);
CREATE INDEX ON sale_items  (product_id);
CREATE INDEX ON purchases   (supplier_id);
CREATE INDEX ON purchase_items (purchase_id);
CREATE INDEX ON purchase_items (product_id);
CREATE INDEX ON payments    (related_sale_id);
CREATE INDEX ON payments    (related_purchase_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- v3 ADDITIONS — run these after the initial schema above
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── ALTER EXISTING TABLES ───────────────────────────────────────────────────

-- sales: VAT breakdown, void support, quote reference
ALTER TABLE sales ADD COLUMN IF NOT EXISTS subtotal      NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS vat_amount    NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS voided        BOOLEAN        NOT NULL DEFAULT FALSE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS void_reason   TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS voided_at     TIMESTAMPTZ;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS quote_id      UUID;

-- Backfill: set subtotal = total for rows created before this migration
UPDATE sales SET subtotal = total WHERE subtotal = 0 AND total > 0;

-- sale_items: cost at time of sale for accurate COGS
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0;

-- products: extended catalogue fields
ALTER TABLE products ADD COLUMN IF NOT EXISTS oem_number       TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS wholesale_price  NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_months  INTEGER        NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS active           BOOLEAN        NOT NULL DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS barcode          TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS vehicle_makes    TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS vehicle_models   TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS year_from        INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS year_to          INTEGER;

-- Backfill: set wholesale_price = selling_price for existing products
UPDATE products SET wholesale_price = selling_price WHERE wholesale_price = 0;

-- suppliers: extended profile
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS email          TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS address        TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS payment_terms  TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS notes          TEXT;


-- ─── NEW TABLE: QUOTATIONS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quotations (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  date              DATE          NOT NULL DEFAULT CURRENT_DATE,
  expiry_date       DATE,
  customer_id       UUID          REFERENCES customers(id) ON DELETE SET NULL,
  status            TEXT          NOT NULL DEFAULT 'draft',  -- draft | sent | converted | expired
  subtotal          NUMERIC(12,2) NOT NULL DEFAULT 0,
  vat_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,
  total             NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes             TEXT,
  converted_sale_id UUID,
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
  synced            BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TRIGGER quotations_updated_at
  BEFORE UPDATE ON quotations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON quotations
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── NEW TABLE: QUOTATION ITEMS ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quotation_items (
  id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  quotation_id  UUID          NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  product_id    UUID          REFERENCES products(id) ON DELETE SET NULL,
  quantity      INTEGER       NOT NULL DEFAULT 1,
  unit_price    NUMERIC(12,2) NOT NULL DEFAULT 0,
  cost_price    NUMERIC(12,2) NOT NULL DEFAULT 0,
  subtotal      NUMERIC(12,2) NOT NULL DEFAULT 0
);

ALTER TABLE quotation_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON quotation_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── NEW TABLE: RETURNS ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS returns (
  id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  original_sale_id UUID          REFERENCES sales(id) ON DELETE SET NULL,
  date             DATE          NOT NULL DEFAULT CURRENT_DATE,
  reason           TEXT          NOT NULL,
  status           TEXT          NOT NULL DEFAULT 'completed',
  subtotal         NUMERIC(12,2) NOT NULL DEFAULT 0,
  vat_amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
  total            NUMERIC(12,2) NOT NULL DEFAULT 0,
  updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
  synced           BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TRIGGER returns_updated_at
  BEFORE UPDATE ON returns
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE returns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON returns
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── NEW TABLE: RETURN ITEMS ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS return_items (
  id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  return_id   UUID          NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  product_id  UUID          REFERENCES products(id) ON DELETE SET NULL,
  quantity    INTEGER       NOT NULL DEFAULT 1,
  unit_price  NUMERIC(12,2) NOT NULL DEFAULT 0,
  cost_price  NUMERIC(12,2) NOT NULL DEFAULT 0,
  subtotal    NUMERIC(12,2) NOT NULL DEFAULT 0
);

ALTER TABLE return_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON return_items
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── NEW TABLE: STOCK MOVEMENTS ───────────────────────────────────────────────
-- Immutable audit log — one row per stock change event.
-- movement_type: sale | purchase | return | transfer_in | transfer_out |
--                void_reversal | adjustment
CREATE TABLE IF NOT EXISTS stock_movements (
  id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id     UUID          REFERENCES products(id) ON DELETE SET NULL,
  movement_type  TEXT          NOT NULL,
  qty_change     INTEGER       NOT NULL,   -- positive = stock in, negative = stock out
  qty_before     INTEGER       NOT NULL DEFAULT 0,
  qty_after      INTEGER       NOT NULL DEFAULT 0,
  location       TEXT,                    -- 'store' | 'warehouse'
  reference_id   UUID,
  reference_type TEXT,
  note           TEXT,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
  synced         BOOLEAN       NOT NULL DEFAULT TRUE
);

-- updated_at = created_at for movements (append-only, never updated)
CREATE TRIGGER stock_movements_updated_at
  BEFORE UPDATE ON stock_movements
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner full access" ON stock_movements
  FOR ALL USING (auth.role() = 'authenticated');


-- ─── NEW INDEXES ──────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_quotations_updated_at   ON quotations    (updated_at);
CREATE INDEX IF NOT EXISTS idx_quotations_customer     ON quotations    (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotations_status       ON quotations    (status);
CREATE INDEX IF NOT EXISTS idx_quotation_items_qid     ON quotation_items (quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_items_pid     ON quotation_items (product_id);
CREATE INDEX IF NOT EXISTS idx_returns_updated_at      ON returns       (updated_at);
CREATE INDEX IF NOT EXISTS idx_returns_sale            ON returns       (original_sale_id);
CREATE INDEX IF NOT EXISTS idx_return_items_rid        ON return_items  (return_id);
CREATE INDEX IF NOT EXISTS idx_return_items_pid        ON return_items  (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_mov_product       ON stock_movements (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_mov_created       ON stock_movements (created_at);
CREATE INDEX IF NOT EXISTS idx_stock_mov_updated       ON stock_movements (updated_at);
CREATE INDEX IF NOT EXISTS idx_stock_mov_reference     ON stock_movements (reference_id);
CREATE INDEX IF NOT EXISTS idx_sales_voided            ON sales         (voided);
CREATE INDEX IF NOT EXISTS idx_products_active         ON products      (active);
CREATE INDEX IF NOT EXISTS idx_products_oem            ON products      (oem_number);
